name: Test Rent Project 

on: 
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps: 
      - name: Clone Repository
        uses: github/checkout@v3
      - name: Install Dependencies
        run: |
          echo: "Running: Installing Dependencies"
          npm install
      - name: Run Linting
        run: |
          echo: "Running Linting Tests"
          npm run lint
        env: 
          CI: true

